#!/bin/bash
JAVA_8_HOME="/usr/lib/jvm/temurin-8-jdk-amd64"
JAVA_17_HOME="/usr/lib/jvm/temurin-17-jdk-amd64"
JAVA_21_HOME="/usr/lib/jvm/temurin-21-jdk-amd64"
JAVA_25_HOME="/usr/lib/jvm/temurin-25-jdk-amd64"

alias cygpath=wslpath
source_file "${HOME}/.bash_functions_wsl2"

export starship_precmd_user_func="set_starship_windows_title" 
eval "$(starship init bash)"

export GRADLE_HOME="/opt/gradle/gradle"
GRADLE_BIN="$GRADLE_HOME/bin"
in_path $GRADLE_BIN || path_prepend "${GRADLE_BIN}"

export JAVA_HOME=$JAVA_25_HOME
JAVA_BIN="$JAVA_HOME/bin"
in_path $JAVA_BIN || path_prepend "${JAVA_BIN}"

export OPENSHIFT_HOME="/opt/openshift"
in_path $OPENSHIFT_HOME || path_prepend "${OPENSHIFT_HOME}"

export DOT_LOCAL_BIN="/home/cspire/.local/bin"
in_path $DOT_LOCAL_BIN || path_prepend "${DOT_LOCAL_BIN}"

# export JAVA_TOOL_OPTIONS="--enable-native-access=ALL-UNNAMED"
export JAVA_8_HOME JAVA_17_HOME JAVA_21_HOME JAVA_25_HOME 


# remove windows adoptium from path if it exists
nullglob_shopt_state=$(shopt -q nullglob; echo $?)
shopt -s nullglob
adoptium_dirs=(/c/Program\ Files/Eclipse\ Adoptium/*/bin)
[[ "$nullglob_shopt_state" -eq 1 ]] && shopt -u nullglob
unset nullglob_shopt_state

for dir in "${adoptium_dirs[@]}"; do
  # Remove trailing slash if present
  dir="${dir%/}"
  in_path "$dir" && path_remove "$dir"
done

export PODMAN_IGNORE_CGROUPSV1_WARNING=
