#!/bin/bash

function gadd() { git add "$@"; }
___git_complete gadd _git_add
function gb() { gbranch "$@"; }
___git_complete gb _git_branch
function gbl() { gbranch -l "$@"; }
___git_complete gbl _git_branch
function gbla() { gbranch -la "$@"; }
___git_complete gbla _git_branch
function gbranch() { git branch "$@"; }
___git_complete gbranch _git_branch
function gco() { git checkout "$@"; }
___git_complete gco _git_checkout
function gcommit() { git commit "$@"; }
___git_complete gcommit _git_commit
function prependJiraToMessage() {
  local msg="$1"
  if [[ ! "$msg" =~ ^[A-Z]+-[0-9]+ ]]; then
      if declare -f jiraTicket > /dev/null; then
        jira_ticket=$(jiraTicket) || {
          >&2 echo "Could not discover jira ticket"
        }
        if [[ -n "$jira_ticket" ]]; then
          >&2 echo -n "Prepend Jira ticket '$jira_ticket' to commit message? [Y/n]: "
          read -r answer
          answer=${answer:-Y}
          if [[ "$answer" =~ ^[Yy]$ ]]; then
            msg="$jira_ticket $msg"
          fi
        fi
      fi
    fi
    echo "$msg"
}

function gcm() { 
  local args msg
  if [ "${1:0:1}" != "-" ]; then
    msg="$1"
    shift;
    args=('-m' "$(prependJiraToMessage "$msg")")
  else
    while [ "$#" -gt 0 ]; do
      case "$1" in
        -m|--message)
          msg="$2"
          args+=("$1" "$(prependJiraToMessage "$msg")")
          shift 2
          break
          ;;
        *)
          args+=("$1")
          ;;
      esac
      shift
    done
  fi
  args+=("$@")
  git commit "${args[@]}";
}

___git_complete gcm _git_commit

function gclone() { 
  local dir=""
  local repo=""
  local git_dir=".git"
  local args=()
  for arg in "$@"; do
    if [[ "$arg" == -* ]]; then
      opts+=("$arg")
    else
      args+=("$arg")
    fi
  done

  if [ "${#args[@]}" -eq 0 ]; then
    >&2 echo "Usage: gclone <repository> [<directory>]"
    return 1
  fi

  # https://git.homeoffice.anfcorp.com/StoresIntegration/spring-cloud-config
  # git@git.homeoffice.anfcorp.com:StoresIntegration/spring-cloud-config.git
  if [[ "${args[0]}" =~ ^https://([^/]+)/(.+)$ ]]; then
    # Extract host and path
    local host="${BASH_REMATCH[1]}"
    local path="${BASH_REMATCH[2]}"
    args[0]="git@${host}:${path}"
  fi

  if [ "${#args[@]}" -eq 1 ]; then
    repo="${args[0]}"
    dir="${repo##*/}"
    dir="${dir%.git}"
    dir="${dir%-java}"
    dir="${dir#anf-}"
  else
    repo="${args[0]}"
    dir="${args[1]}"
  fi
  mkdir -p "$dir" || return 1
  cd "$dir" || return 2
  git clone --bare --single-branch "${opts[@]}" "$repo" "$git_dir"
  local cloned=$?
  [[ $cloned -ne 0 ]] && return $cloned
  # echo "gitdir: ./$repo_dir" > .git
  git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*" || return $?
  git fetch origin || return $?
  local remote_branch remote local_branch
  remote_branch=$(git rev-parse --abbrev-ref refs/remotes/origin/HEAD) || return $?
  remote=$(git remote) || return $?
  local_branch=${remote_branch##"$remote/"}
  if git rev-parse --verify --quiet "$local_branch" ; then
    git branch --set-upstream-to="$remote_branch" "$local_branch" || return $?
  fi 
  # cd "$dir" || return 1
}
___git_complete gclone _git_clone

function gdiff() { git diff "$@"; }
___git_complete gdiff _git_diff

function gls() { git ls-files "$@"; }
# list files that are modified
# shellcheck disable=SC2120
function glsm() { git ls-files -m "$@"; }
# list files that are untracked by git
# shellcheck disable=SC2120
function glso() { git ls-files -o --exclude-standard "$@"; }
function glsu() { git ls-files -u "$@"; }
# list files that are added/staged for commit
function glsa() { git diff --name-only --cached; }
___git_complete glsa _git_diff
function gmerge() { git mergetool "$@"; }
___git_complete gmerge _git_mergetool
function gpull() { git pull "$@"; }
___git_complete gpull _git_pull
function gpush() { git push "$@"; }
___git_complete gpush _git_push
function gstash() { git stash "$@"; }
___git_complete gstash _git_stash
function gstat() { gstatus "$@"; }
___git_complete gstat _git_status
function gstatus() { git status "$@"; }
___git_complete gstatus _git_status
function gwt() { git worktree "$@"; }
___git_complete gwt _git_worktree
function gwtl() { git worktree list "$@"; }

function gwtr() {
  # git worktree remove
  local args=("$@")
  local topDir
  topDir=$(git rev-parse --git-common-dir)/..
  git worktree remove "$@";
  [[ -d $PWD ]] && return 
  cd "$topDir" || return $?
}

function gwtcd() {
  local cdBranch=$1
  allWorktrees=$(git worktree list --porcelain | grep -e ^worktree -e ^branch )
  while read -r line; do
    key=${line% *}
    value=${line#* }
    case $key in
      worktree*)
        wt=$value
      ;;
      branch*)
        branchName="${value//refs\/heads\//}"
      ;;
      *)
        # echo "ignoring others"
      ;;
    esac
    if [ "${branchName}" == "${cdBranch}" ]; then cd "$wt" || return 1; return; fi
  done <<< "${allWorktrees[@]}"  
}

function gwts() { cdwt; }

function cdwt() {
  # set -x
  echo "git worktree select: UI to select the existing worktrees with some management options" > /dev/null
  local wt allWorktrees wt keyValue wtMaxLength branchMaxLength currentbranch
  wtMaxLength=0
  branchMaxLength=0
  name="(c)d/[ENTER] | (r)remove | (q)uit"
  while : ; do
    unset keyValue
    declare -A keyValue
    currentbranch=$(git branch --show-current)
    allWorktrees=$(git worktree list --porcelain | grep -e ^worktree -e ^branch )
    if [ "${#allWorktrees}" -le 0 ]; then return 1; fi
    while read -r line; do
      key=${line% *}
      value=${line#* }
      case $key in
        worktree*)
          wt=$value
          wtLength=${#wt}
          wtMaxLength=$(( wtLength > wtMaxLength ? wtLength : wtMaxLength ))
        ;;
        branch*)
          branchName="${value//refs\/heads\//}"
          keyValue["$branchName"]="$wt"
          branchLength=${#branchName}
          branchMaxLength=$(( branchLength > branchMaxLength ? branchLength : branchMaxLength ))
        ;;
        *)
          # echo "ignoring others"
        ;;
      esac
    done <<< "${allWorktrees[@]}"

    [[ "${#keyValue[@]}" -eq 1 ]] && cd "${keyValue[@]}" && return 0;
    [[ "${#keyValue[@]}" -eq 0 ]] && echo "no worktress" && return 1;

    local BRANCH_INDEX=1
    local branchNumber=0
    mapfile -t sortedBranchName < <( for branchName in "${!keyValue[@]}"; do echo "$branchName"; done | sort)

    for i in "${sortedBranchName[@]}"; do 
      ((branchNumber+=1))
      if [ "$i" == "$currentbranch" ]; then 
        BRANCH_INDEX=$branchNumber
        break;
      fi
    done;
    
    wt=$(iselect -n "$name" -p $BRANCH_INDEX -kc -kr -K -a -e "$(for branchName in "${sortedBranchName[@]}"; do printf "<s:%s>%-${branchMaxLength}s %s\n" "${branchName}" "${branchName}" "${keyValue[$branchName]}"; done)")
    if [ "${#wt}" -eq 0 ]; then break; fi
    selectedCommand=${wt%:*}
    selectedBranch=${wt#*:}
    case "$selectedCommand" in
      RETURN | c)
        cd "${keyValue[$selectedBranch]}" || return 2
        break
        ;;
      r)
        if ! gwtr "${keyValue[$selectedBranch]}"; then
          cd "${keyValue[$selectedBranch]}" || return 4
          echo "-------- modified"
          glsm
          echo "-------- other"
          glso
          echo "--------"
          echo 'find . -name '\''*.orig'\'' -delete'
          echo "gwtr '${keyValue[$selectedBranch]##*/}' --force";
          break; 
        fi
        if [ "$selectedBranch" = "$currentbranch" ]; then
          local master="${keyValue['master']}"
          [[ -d "$master" ]] && { cd "$master" || return 8; }
        fi
        ;;
      *)
        echo "breaking"
        break;;
    esac
  done
  # set +x
}

function gwtcheck() {
  if [ -d ./.git ]; then
    echo 1>&2 ".git is a directory, is this a worktree?"
    return 1
  fi
}

function gwttarget() {
  if ! worktree_target="$(git rev-parse --show-toplevel)"; then
    echo 1>&2 "Could not resolve top level directory, is this a worktree?"
    return 2
  fi
  echo "$worktree_target"
}

function gwtrepo() {
  if ! repository_target="$(git rev-parse --git-dir)"; then
    echo 1>&2 "Could not resolve git directory, is this a worktree?"
    return 3
  fi
  echo "$repository_target"
}

function gwtrel() {
  gwtcheck || return $?
  worktree_target=$(gwttarget) || return $?
  repository_target=$(gwtrepo) || return $?
  path_worktree_to_repo=$(realpath --relative-to="$worktree_target" "$repository_target")
  echo "gitdir: $path_worktree_to_repo" > "$worktree_target/.git"
}

function gwtabs() {
  gwtcheck || return $?
  worktree_target=$(gwttarget) || return $?
  repository_target=$(gwtrepo) || return $?
  echo "gitdir: $repository_target" > "$worktree_target/.git"
}

function gwta() {
    local branch=$1
    shift
    local top remote
    top=$(git rev-parse --git-common-dir)/..
    branch_flag=-b
    remote=$(git remote)
    # local | remote | flag
    #  true    true     none
    #  true    false    none
    #  false   true     none
    #  false   false    -b
    if git show-ref --verify --quiet refs/heads/"$branch"; then
      # branch exist locally
      unset branch_flag
    elif git ls-remote --exit-code --heads "$remote" "$branch" > /dev/null; then
      # branch exists remotely and local doesn't exist
      unset branch_flag
    fi
    git worktree add "$top/$branch" $branch_flag "$branch" "$@";
}

function gaddwt() {
  [ $# -ne 1 ] \
    && echo usage > /dev/null \
    && echo -e "\nusage: ${FUNCNAME[0]} <branch>\n" \
    && echo -e "\t1. Adds branch worktree." \
    && echo -e "\t2. Changes the directory to the added worktree." \
    && echo -e "\t3. Tracks that branch." \
    && return 1
      
    gwta "$1" || return 1
    local top
    top=$(git rev-parse --git-common-dir)/..
    cd "$top/$1" || return 2
    gwtrel || return 3
}

function gsetup() {
  local upstream branch
  upstream=$(git rev-parse --abbrev-ref --symbolic-full-name "@{u}" 2> /dev/null )
  branch=$(git rev-parse --abbrev-ref HEAD)
  remote=$(git remote)
  [[ "$upstream" = "$remote/$branch" ]] && return
  if git ls-remote --exit-code --heads "$remote" "$branch" &> /dev/null; then
    git branch --set-upstream-to="$remote/$branch"
  else 
    git push -u "$remote" "$branch"
  fi
  
}

function grepo() {
  local remote
  remote="$(git remote)"
  # git remote get-url "$remote" | sed -e 's#:#/#' -e 's#git@#https://#' -e 's#.git$##'
  local url
  url=$(git remote get-url "$remote")
  url=${url/:/\/}
  url=${url/git@/https://}
  url=${url%.git}
  echo "$url"
}
