#!/bin/bash
command_not_found_handle() {
  # inspired somewhat by: https://www.linuxjournal.com/content/bash-command-not-found
  local cmd="$1.exe"
  # ability to run windows command without exe extension
  if command -v "$cmd" &> /dev/null; then
    "$cmd" "${@:2}"
    return $?
  # this should be default behavior: from /etc/bash.bashrc
  elif [ -x /usr/lib/command-not-found ] || [ -x /usr/share/command-not-found/command-not-found ]; then
    # check because c-n-f could've been removed in the meantime
    if [ -x /usr/lib/command-not-found ]; then
      /usr/lib/command-not-found -- "$1"
      return $?
    elif [ -x /usr/share/command-not-found/command-not-found ]; then
      /usr/share/command-not-found/command-not-found -- "$1"
      return $?
    else
      printf "%s: command not found\n" "$1" >&2
      return 127
    fi
  else
    return 127;
  fi
}

function idea() {
  [[ -e pom.xml ]] && 
  local dist="$HOME/.cache/JetBrains/RemoteDev/dist"
  local ij
  ij=$(jetbrains) || return $?

  local exe_path="$dist/$ij/bin/idea.sh"
  # local exe_path="$dist/$ij/bin/remote-dev-server.sh"
  if [[ ! -x "$exe_path" ]]; then
    echo "Executable not found: $exe_path" >&2
    return 2
  fi
  [[ -e pom.xml ]] && [[ ! -e .idea/.name ]] && {
    projectName=$(xmllint --xpath '/*[local-name()="project"]/*[local-name()="artifactId"]/text()' pom.xml) && mkdir -p .idea && echo "$projectName" > .idea/.name;
  }

  "$exe_path" "$@"
}

function remote-dev-server() {
  local dist="$HOME/.cache/JetBrains/RemoteDev/dist"
  local ij
  ij=$(jetbrains) || return $?

  # local exe_path="$dist/$ij/bin/idea.sh"
  local exe_path="$dist/$ij/bin/remote-dev-server.sh"
  if [[ ! -x "$exe_path" ]]; then
    echo "Executable not found: $exe_path" >&2
    return 2
  fi

  "$exe_path" "$@"
}


jetbrains() {
  local dist="$HOME/.cache/JetBrains/RemoteDev/dist"
  local jetbrains

  # find:
  #  -maxdepth 1 to not recurse into subdirs
  #  -name to only find dirs that match the pattern
  #  -type d to only find dirs
  #  -printf '%P\n' to print only the dir name without the path
  # sort:
  #  -t splits to 2 groups.
  #  -k says 2nd group starting with the 1st character.
  #  -V is symantic version sort
  jetbrains=$(find "$dist" -maxdepth 1 -name "*_idea*-*" -type d -printf '%P\n' | sort -V -t'-' -k 2.1 | tail -1)

  if [[ -z "$jetbrains" ]]; then
    echo "No IntelliJ IDEA version found in $dist" >&2
    return 1
  fi
  echo "$jetbrains"
}

j8() {
  JAVA_HOME=$JAVA_8_HOME "$@"
}

j17() {
  JAVA_HOME=$JAVA_17_HOME "$@"
} 

j21() {
  JAVA_HOME=$JAVA_21_HOME "$@"
} 
