# dotfiles
:icons: font
:toc: auto

## Overview

This is very much focused on using Cygwin Bash in Windows. Git. Maven/Java.  Some of it is portable, some of it is not. Some of it will work in other Bash shells like Git Bash. Some of it relies on packages that are not available in Git Bash. YMMV.

WARNING: This is very much a WIP. I had only recently discovered that others were managing/sharing dotfiles. I wasn't aware of any tools and I had my own hacked together using bare git but wasn't "sharable" (it had secrets). I kind of forced usage of `chezmoi` to see how far I could get.  I might refactor this solution to use `yadm` or `flow` if I continue to find `chezmoi` continues to be problematic.  `yadm` is largely a wrapper for `git` with some added features.  `flow` seems really simple but appears to rely on symlinks.

## chezmoi

It appears chezmoi is the more popular dotfile managers available ( https://dotfiles.github.io/utilities/ ), but it does not exactly play nice with Cygwin.  Alternatives that might prove easier to configure or may use out of the box include `yadm` and `flow`. Cygwin actually has a `flow` package that is available to install from the Cygwin installer.


chezmoi provides a comparison table with some other tools: https://www.chezmoi.io/comparison-table/


NOTE: In the source examples, `cm` is an alias to `chezmoi`

[source,bash]
----
alias cm='chezmoi'
----

### download/install

Not the only way to install it, but it is is, afaik, availaible on windows 10/11 by default. It might require patches/upgrades to OS.  There are other install methods available. See https://www.chezmoi.io/

[source,bash]
----
winget install twpayne.chezmoi
----

### Cygwin Config

WARNING: It is not possible to output directly to chezmoi.json because `chezmoi dump-config`
attempts to read the config during output and errors out.

NOTE: Json is the default format for dump-config.

I was able to create a config file from the default configuration and modify it.

[source,bash]
----
_config_dir=/c/Users/$USER/.config/chezmoi
mkdir -p $_config_dir ~/.local/share/chezmoi ~/.cache/chezmoi
cm dump-config | sed 's#/Users/#/cygwin64/home/#' > $_config_dir/chezmoi.dump.json
mv $_config_dir/chezmoi.dump.json $_config_dir/chezmoi.json
----

### init/apply

[source,bash]
----
cm init --apply christopher-spires
----

### bash autocomplete

[source,bash]
----
cm completion bash > ~/.bash_completion.d/chezmoi-completion.bash
----

### Issues

The version at the time of writing this did not properly read yaml or toml configurations inside a Cygwin environment.  Json was the only config format that appeared to work.

`cm cd` does not work.

----
chezmoi: /bin/bash: exec: "/bin/bash": executable file not found in %PATH%
----
